name: Deploy with rsync

on: workflow_dispatch

permissions: write-all

env:
    APP_ENV: prod
    APP_VERSION: ${{ github.ref_name }}

jobs:
    rsync_upload:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3

            - name: Setup env
              run: |
                  echo "APP_ENV=prod" >> .env.local
                  echo "APP_DEBUG=0" >> .env.local
                  touch .env.prod.local
                  echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.prod.local
                  echo "MAILER_DSN=${{ secrets.MAILER_DSN }}" >> .env.prod.local
                  echo "DEFAULT_URI=${{ secrets.DEFAULT_URI }}" >> .env.prod.local
                  echo "MAILER_FROM_ADDRESS=${{ secrets.MAILER_FROM_ADDRESS }}" >> .env.prod.local

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: locked
                  composer-options: "--ignore-platform-reqs --optimize-autoloader --no-dev"

            - name: Import assets
              run: |
                  php bin/console sass:build
                  php bin/console asset-map:compile
                  php bin/console assets:install

            - name: Optimize app
              run: |
                  composer dump-env prod
                  composer dump-autoload --optimize --classmap-authoritative
                  php bin/console cache:warmup

                  # Copy .htaccess
                  cp docker/apache/.htaccess public/.htaccess

                  # Optimize PHP
                  cp docker/apache/php_prod.ini public/php.ini
                  echo "opcache.preload=${{ secrets.APP_PATH }}/config/preload.php" >> public/php.ini

                  # Register custom public/php.ini in public/.htaccess
                  echo "suPHP_ConfigPath ${{ secrets.APP_PATH }}/public/" >> public/.htaccess

            - name: Whitelist IP address
              uses: d9beuD/o2switch-whitelisting@v1.0.3
              with:
                  o2switch_username: ${{ secrets.SSH_USER }}
                  o2switch_password: ${{ secrets.SSH_PASSWORD }}
                  o2switch_host: ${{ secrets.SSH_HOST }}
                  otp_secret: ${{ secrets.O2SWITCH_OTP_SECRET }}

            - name: Deploy with rsync
              uses: easingthemes/ssh-deploy@v5.1.0
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  # Updates are based on file hash, not time + size
                  ARGS: "-rlgoDzvc -i --delete"
                  SOURCE: "./"
                  REMOTE_HOST: ${{ secrets.SSH_HOST }}
                  REMOTE_USER: ${{ secrets.SSH_USER }}
                  TARGET: ${{ secrets.APP_PATH }}/
                  EXCLUDE: ".git*, public/assets/upload/*"
